### ISSUE TITLE
ERR next is not a function

### ISSUE THREAD

**Issue by tomasrudh** [Maaaarden/VSCode-AzureAutomationExtension#39]
After I have configured the extension this shows up in the developer console:

ERR next is not a function: TypeError: next is not a function
    at Request._callback (c:\Users\tomas.rudh\.vscode\extensions\awesomeautomationteam.azureautomation-1.0.2\modules\AzureAutomation.js:103:16)
    at Request.self.callback (c:\Users\tomas.rudh\.vscode\extensions\awesomeautomationteam.azureautomation-1.0.2\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (c:\Users\tomas.rudh\.vscode\extensions\awesomeautomationteam.azureautomation-1.0.2\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (c:\Users\tomas.rudh\.vscode\extensions\awesomeautomationteam.azureautomation-1.0.2\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by NickolajA** [comment]
I get the same, unfortunately. Can't get this extension to work at all.

**Comment by Maaaarden** [comment]
Hi @tomasrudh and @NickolajA 

First - Sorry for the lack of response on this matter. 
Second - I'm not quite sure what triggers this error for you guys - i've just tried installing fresh on my laptop, no issues connecting.

Longshot - is the Automation Account empty? Meaning, does it contain any runbooks?

Regards
